networks:
  pilota-proxy:
    external: true
    name: pilota-proxy

services:
  pulse:
    build:
      context: ../..
      dockerfile: playground/pulse/Dockerfile
    volumes:
      - ./src:/app/playground/pulse/src
    environment:
      LARAVEL_API_URL: http://laravel:8000/api
      NEXT_PUBLIC_TOLGEE_API_URL: http://tolgee.localhost
      NEXT_PUBLIC_TOLGEE_API_KEY: ${NEXT_PUBLIC_TOLGEE_API_KEY:-}
      NEXT_PUBLIC_SENTRY_DSN: ${NEXT_PUBLIC_SENTRY_DSN:-}
    networks:
      - default
      - pilota-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pulse-${BRANCH:-dev}.rule=Host(`${BRANCH:-dev}-pulse.localhost`)"
      - "traefik.http.routers.pulse-${BRANCH:-dev}.entrypoints=web"
      - "traefik.http.services.pulse-${BRANCH:-dev}.loadbalancer.server.port=3001"
