import type { PcProfile, Assignment, Repair, Order, Alert } from './resources'

export const mockPcProfiles: PcProfile[] = [
    { id: 1,  role: 'Développeur',              model_tier: 'performance', model_name: 'HP ZBook Power G10',      cpu: 'Intel Core i7-13700H', ram: '32 Go DDR5',  storage: '1 To NVMe',    gpu: 'NVIDIA RTX 2000 Ada',  screens: 2, screen_spec: '27" 4K',    profile_ram: '32 Go', total: 14, stock: 9  },
    { id: 2,  role: 'Développeur mobile Apple', model_tier: 'performance', model_name: 'MacBook Pro 16" M3 Pro',  cpu: 'Apple M3 Pro 12c',     ram: '36 Go',       storage: '1 To SSD',     gpu: 'GPU 18c intégré',      screens: 2, screen_spec: '27" 5K',    profile_ram: '36 Go', total: 6,  stock: 4  },
    { id: 3,  role: 'UX Designer',              model_tier: 'performance', model_name: 'MacBook Pro 14" M3',      cpu: 'Apple M3 8c',          ram: '24 Go',       storage: '512 Go SSD',   gpu: 'GPU 10c intégré',      screens: 2, screen_spec: '27" 4K',    profile_ram: '24 Go', total: 4,  stock: 2  },
    { id: 4,  role: 'Technicien',               model_tier: 'standard',    model_name: 'HP EliteBook 840 G10',    cpu: 'Intel Core i5-1335U',  ram: '16 Go DDR4',  storage: '512 Go NVMe',  gpu: 'Intel Iris Xe',        screens: 1, screen_spec: '24" FHD',   profile_ram: '16 Go', total: 18, stock: 11 },
    { id: 5,  role: 'Commercial',               model_tier: 'standard',    model_name: 'HP EliteBook 840 G10',    cpu: 'Intel Core i5-1335U',  ram: '16 Go DDR4',  storage: '512 Go NVMe',  gpu: 'Intel Iris Xe',        screens: 1, screen_spec: '24" FHD',   profile_ram: '16 Go', total: 22, stock: 14 },
    { id: 6,  role: 'Chef de projet',           model_tier: 'standard',    model_name: 'HP EliteBook 1040 G10',   cpu: 'Intel Core i7-1365U',  ram: '32 Go DDR4',  storage: '1 To NVMe',    gpu: 'Intel Iris Xe',        screens: 1, screen_spec: '27" QHD',   profile_ram: '32 Go', total: 8,  stock: 5  },
    { id: 7,  role: 'Responsable',              model_tier: 'standard',    model_name: 'HP EliteBook 1040 G10',   cpu: 'Intel Core i7-1365U',  ram: '16 Go DDR4',  storage: '512 Go NVMe',  gpu: 'Intel Iris Xe',        screens: 1, screen_spec: '27" QHD',   profile_ram: '16 Go', total: 6,  stock: 4  },
    { id: 8,  role: 'Administrateur réseau',    model_tier: 'performance', model_name: 'HP ZBook Fury G10',       cpu: 'Intel Core i9-13900HX',ram: '64 Go DDR5',  storage: '2 To NVMe',    gpu: 'NVIDIA RTX 3000 Ada',  screens: 2, screen_spec: '27" 4K + 24"', profile_ram: '64 Go', total: 4,  stock: 3  },
    { id: 9,  role: 'Comptable',                model_tier: 'standard',    model_name: 'HP EliteBook 840 G10',    cpu: 'Intel Core i5-1335U',  ram: '16 Go DDR4',  storage: '256 Go NVMe',  gpu: 'Intel Iris Xe',        screens: 1, screen_spec: '24" FHD',   profile_ram: '16 Go', total: 10, stock: 6  },
]

export const mockAssignments: Assignment[] = [
    { id: 1,  employee: 'Lucas Martin',     email: 'l.martin@pilota.dev',     team: 'Dev Backend',   department: 'Technique', model: 'HP ZBook Power G10',     serial: 'ZBP-2024-001', assigned_at: '2024-03-15', status: 'active'   },
    { id: 2,  employee: 'Camille Dubois',   email: 'c.dubois@pilota.dev',     team: 'Dev Frontend',  department: 'Technique', model: 'HP ZBook Power G10',     serial: 'ZBP-2024-002', assigned_at: '2024-03-15', status: 'active'   },
    { id: 3,  employee: 'Thomas Bernard',   email: 't.bernard@pilota.dev',    team: 'Mobile iOS',    department: 'Technique', model: 'MacBook Pro 16" M3 Pro', serial: 'MBP-2024-001', assigned_at: '2024-04-01', status: 'active'   },
    { id: 4,  employee: 'Sophie Laurent',   email: 's.laurent@pilota.dev',    team: 'UX/UI',         department: 'Technique', model: 'MacBook Pro 14" M3',     serial: 'MBP-2024-002', assigned_at: '2024-04-01', status: 'active'   },
    { id: 5,  employee: 'Nicolas Petit',    email: 'n.petit@pilota.dev',      team: 'Support N1',    department: 'Technique', model: 'HP EliteBook 840 G10',   serial: 'EBK-2024-001', assigned_at: '2024-02-10', status: 'repair'   },
    { id: 6,  employee: 'Emma Rousseau',    email: 'e.rousseau@pilota.dev',   team: 'Commercial Est',department: 'Commerce',  model: 'HP EliteBook 840 G10',   serial: 'EBK-2024-002', assigned_at: '2024-01-20', status: 'active'   },
    { id: 7,  employee: 'Antoine Moreau',   email: 'a.moreau@pilota.dev',     team: 'Commercial Sud',department: 'Commerce',  model: 'HP EliteBook 840 G10',   serial: 'EBK-2024-003', assigned_at: '2024-01-20', status: 'active'   },
    { id: 8,  employee: 'Julie Simon',      email: 'j.simon@pilota.dev',      team: 'Gestion',       department: 'Finance',   model: 'HP EliteBook 840 G10',   serial: 'EBK-2022-015', assigned_at: '2022-09-01', status: 'active'   },
    { id: 9,  employee: 'Marc Lefebvre',    email: 'm.lefebvre@pilota.dev',   team: 'Infra',         department: 'Technique', model: 'HP ZBook Fury G10',      serial: 'ZBF-2024-001', assigned_at: '2024-05-10', status: 'active'   },
    { id: 10, employee: 'Léa Girard',       email: 'l.girard@pilota.dev',     team: 'PMO',           department: 'Direction', model: 'HP EliteBook 1040 G10',  serial: 'EBM-2024-001', assigned_at: '2024-03-01', status: 'active'   },
    { id: 11, employee: 'Pierre Bonnet',    email: 'p.bonnet@pilota.dev',     team: 'Dev Backend',   department: 'Technique', model: 'HP ZBook Power G10',     serial: 'ZBP-2024-003', assigned_at: '2024-03-15', status: 'active'   },
    { id: 12, employee: 'Clara Henry',      email: 'c.henry@pilota.dev',      team: 'Support N2',    department: 'Technique', model: 'HP EliteBook 840 G10',   serial: 'EBK-2024-004', assigned_at: '2024-02-10', status: 'active'   },
    { id: 13, employee: 'Hugo Blanc',       email: 'h.blanc@pilota.dev',      team: 'Commercial Nord',department: 'Commerce', model: 'HP EliteBook 840 G10',   serial: 'EBK-2021-007', assigned_at: '2021-06-15', status: 'active'   },
    { id: 14, employee: 'Manon Garnier',    email: 'm.garnier@pilota.dev',    team: 'Finance',       department: 'Finance',   model: 'HP EliteBook 840 G10',   serial: 'EBK-2023-011', assigned_at: '2023-04-01', status: 'active'   },
    { id: 15, employee: 'Kevin Faure',      email: 'k.faure@pilota.dev',      team: 'Mobile iOS',    department: 'Technique', model: 'MacBook Pro 16" M3 Pro', serial: 'MBP-2024-003', assigned_at: '2024-04-01', status: 'returned' },
]

export const mockRepairs: Repair[] = [
    { id: 1, ticket: 'REP-2025-018', employee: 'Nicolas Petit',  team: 'Support N1',     device: 'HP EliteBook 840 G10', serial: 'EBK-2024-001', issue: 'Dalle LCD brisée, suite à chute',              status: 'in_progress',   technician: 'Marc Lefebvre',  opened_at: '2025-05-12', closed_at: null,         parts: ['Dalle LCD 14" FHD']                           },
    { id: 2, ticket: 'REP-2025-017', employee: 'Hugo Blanc',     team: 'Commercial Nord', device: 'HP EliteBook 840 G10', serial: 'EBK-2021-007', issue: 'Batterie ne tient plus de charge',            status: 'waiting_parts', technician: 'Marc Lefebvre',  opened_at: '2025-05-08', closed_at: null,         parts: ['Batterie HP HS04 68Wh']                       },
    { id: 3, ticket: 'REP-2025-016', employee: 'Emma Rousseau',  team: 'Commercial Est',  device: 'HP EliteBook 840 G10', serial: 'EBK-2024-002', issue: 'Clavier partiellement non fonctionnel',       status: 'open',          technician: null,             opened_at: '2025-05-15', closed_at: null,         parts: []                                              },
    { id: 4, ticket: 'REP-2025-014', employee: 'Julie Simon',    team: 'Gestion',         device: 'HP EliteBook 840 G10', serial: 'EBK-2022-015', issue: 'SSD dégradé, secteurs défectueux détectés',   status: 'closed',        technician: 'Marc Lefebvre',  opened_at: '2025-04-20', closed_at: '2025-05-02', parts: ['SSD Samsung 870 EVO 512Go']                   },
    { id: 5, ticket: 'REP-2025-011', employee: 'Lucas Martin',   team: 'Dev Backend',     device: 'HP ZBook Power G10',   serial: 'ZBP-2024-001', issue: 'Ventilateur bruyant, surchauffe sous charge',  status: 'closed',        technician: 'Clara Henry',    opened_at: '2025-04-05', closed_at: '2025-04-12', parts: ['Ventilateur HP ZBook G10']                    },
    { id: 6, ticket: 'REP-2025-019', employee: 'Manon Garnier',  team: 'Finance',         device: 'HP EliteBook 840 G10', serial: 'EBK-2023-011', issue: 'Port USB-C ne charge plus',                   status: 'open',          technician: null,             opened_at: '2025-05-16', closed_at: null,         parts: []                                              },
]

export const mockOrders: Order[] = [
    { id: 1, ref: 'CMD-2025-042', type: 'hardware',    item: 'HP ZBook Power G10 (Développeur)',       quantity: 5,  reason: 'Remplacement parc vieillissant Dev Backend',        requested_by: 'Marc Lefebvre',  status: 'ordered',   created_date: '2025-05-10' },
    { id: 2, ref: 'CMD-2025-041', type: 'hardware',    item: 'MacBook Pro 16" M3 Pro (Dev Mobile)',    quantity: 2,  reason: 'Nouvelles recrues équipe iOS',                       requested_by: 'Léa Girard',     status: 'approved',  created_date: '2025-05-08' },
    { id: 3, ref: 'CMD-2025-040', type: 'parts',       item: 'Batterie HP HS04 68Wh',                  quantity: 3,  reason: 'Stock pièces de remplacement REP-2025-017',          requested_by: 'Marc Lefebvre',  status: 'pending',   created_date: '2025-05-14' },
    { id: 4, ref: 'CMD-2025-039', type: 'hardware',    item: 'HP EliteBook 840 G10 (Commercial)',       quantity: 4,  reason: 'Extension équipe commerciale région Sud',           requested_by: 'Léa Girard',     status: 'delivered', created_date: '2025-04-22' },
    { id: 5, ref: 'CMD-2025-037', type: 'parts',       item: 'Dalle LCD HP EliteBook 14" FHD',          quantity: 2,  reason: 'Stock pièces REP en cours',                          requested_by: 'Clara Henry',    status: 'ordered',   created_date: '2025-05-01' },
    { id: 6, ref: 'CMD-2025-035', type: 'consumable',  item: 'Câbles USB-C Thunderbolt 4 (2m)',         quantity: 20, reason: 'Réapprovisionnement parc accessoires',               requested_by: 'Nicolas Petit',  status: 'delivered', created_date: '2025-04-15' },
    { id: 7, ref: 'CMD-2025-043', type: 'hardware',    item: 'Écran Dell U2722D 27" QHD',              quantity: 8,  reason: 'Équipement nouvelles positions open space Toulouse', requested_by: 'Marc Lefebvre',  status: 'pending',   created_date: '2025-05-17' },
]

export const mockAlerts: Alert[] = [
    { id: 1, type: 'warranty',    severity: 'critical', device: 'HP EliteBook 840 G10', serial: 'EBK-2021-007', employee: 'Hugo Blanc',    description: 'Garantie expirée depuis 3 mois',                     due_date: '2025-02-15', status: 'active'      },
    { id: 2, type: 'warranty',    severity: 'critical', device: 'HP EliteBook 840 G10', serial: 'EBK-2022-015', employee: 'Julie Simon',   description: 'Garantie expire dans 12 jours',                      due_date: '2025-05-31', status: 'active'      },
    { id: 3, type: 'age',         severity: 'warning',  device: 'HP EliteBook 840 G10', serial: 'EBK-2021-007', employee: 'Hugo Blanc',    description: 'Appareil en service depuis 4 ans · remplacement conseillé', due_date: '2025-06-15', status: 'active' },
    { id: 4, type: 'age',         severity: 'warning',  device: 'HP EliteBook 840 G10', serial: 'EBK-2022-015', employee: 'Julie Simon',   description: 'Appareil en service depuis 3 ans · préparer le remplacement', due_date: '2025-09-01', status: 'active' },
    { id: 5, type: 'performance', severity: 'warning',  device: 'HP EliteBook 840 G10', serial: 'EBK-2023-011', employee: 'Manon Garnier', description: 'Disque dur à 87% de capacité · nettoyage recommandé', due_date: '2025-05-30', status: 'active' },
    { id: 6, type: 'warranty',    severity: 'info',     device: 'HP ZBook Power G10',   serial: 'ZBP-2024-001', employee: 'Lucas Martin',  description: 'Garantie expire dans 10 mois',                       due_date: '2026-03-15', status: 'active'      },
    { id: 7, type: 'security',    severity: 'critical', device: 'HP EliteBook 840 G10', serial: 'EBK-2021-007', employee: 'Hugo Blanc',    description: 'Dernière mise à jour sécurité : 142 jours',          due_date: '2025-05-19', status: 'active'      },
    { id: 8, type: 'age',         severity: 'info',     device: 'HP EliteBook 840 G10', serial: 'EBK-2023-011', employee: 'Manon Garnier', description: 'Appareil en service depuis 2 ans',                   due_date: '2026-04-01', status: 'acknowledged' },
]
