include:
  - playground/backends/laravel/docker-compose.yml
  - playground/backends/nhost/docker-compose.yml
  - playground/backends/supabase/docker-compose.yml
  - playground/nuxt/docker-compose.yml
  - playground/pulse/docker-compose.yml
  - playground/vota/docker-compose.yml
  - playground/gearup/docker-compose.yml
