import type { Project, Objective, Delivery, Mission, Absence, DevOpsNeed, WeekInfo, Revenue, Contract } from './resources'

export const mockProjects: Project[] = [
    {
        id: 1,
        name: 'Gearup',
        status: 'ok',
        open_bugs: 0,
        deployments: ['v1.0.0 — en prod'],
        team: 'Frontend',
        url: 'http://localhost:3003',
        sentry_issues: 2,
        sentry_criticals: 0,
        updated_at: new Date().toISOString(),
    },
    {
        id: 2,
        name: 'Vota',
        status: 'ok',
        open_bugs: 1,
        deployments: ['v1.0.0 — en prod'],
        team: 'Frontend',
        url: 'http://localhost:3002',
        sentry_issues: 0,
        sentry_criticals: 0,
        updated_at: new Date().toISOString(),
    },
    {
        id: 3,
        name: 'Shoplab',
        status: 'warning',
        open_bugs: 3,
        deployments: ['v1.0.0 — en prod'],
        team: 'Frontend',
        url: 'http://localhost:3010',
        sentry_issues: 7,
        sentry_criticals: 0,
        updated_at: new Date().toISOString(),
    },
    {
        id: 4,
        name: 'Grosdata',
        status: 'warning',
        open_bugs: 4,
        deployments: ['v2.4.1 — mercredi'],
        team: 'Backend',
        url: null,
        sentry_issues: 14,
        sentry_criticals: 1,
        updated_at: new Date().toISOString(),
    },
    {
        id: 5,
        name: 'Nexeren',
        status: 'ok',
        open_bugs: 0,
        deployments: [],
        team: 'Fullstack',
        url: null,
        sentry_issues: 3,
        sentry_criticals: 0,
        updated_at: new Date().toISOString(),
    },
    {
        id: 6,
        name: 'Skera',
        status: 'critical',
        open_bugs: 9,
        deployments: ['v1.9.0 — ce soir'],
        team: 'Fullstack',
        url: null,
        sentry_issues: 41,
        sentry_criticals: 3,
        updated_at: new Date().toISOString(),
    },
    {
        id: 7,
        name: 'Nota',
        status: 'ok',
        open_bugs: 1,
        deployments: ['v3.2.0'],
        team: 'Mobile',
        url: null,
        sentry_issues: 5,
        sentry_criticals: 0,
        updated_at: new Date().toISOString(),
    },
    {
        id: 8,
        name: 'Horizon',
        status: 'inactive',
        open_bugs: 0,
        deployments: [],
        team: 'Backend',
        url: null,
        sentry_issues: 0,
        sentry_criticals: 0,
        updated_at: new Date().toISOString(),
    },
]

export const mockObjectives: Objective[] = [
    {
        id: 1,
        person: 'Gaetan',
        avatar: null,
        week: 21,
        year: 2026,
        focus: 'Finaliser le dashboard Pulse — sections complètes avec vraies données',
        blockers: ['API Laravel en attente de déploiement'],
        wins: ['OSDD validé sur Gearup', 'Sentry intégré sur 4 frontends', 'Pilota SDK v1 stable'],
    },
    {
        id: 2,
        person: 'Alice',
        avatar: null,
        week: 21,
        year: 2026,
        focus: 'Refonte module commandes Grosdata — migration v2.4',
        blockers: [],
        wins: ['Migration BDD terminée sans downtime', 'Tests de charge OK'],
    },
    {
        id: 3,
        person: 'Bob',
        avatar: null,
        week: 21,
        year: 2026,
        focus: 'Audit sécurité Nexeren — livrables ANSSI',
        blockers: ['Accès prod en attente validation DSI'],
        wins: [],
    },
    {
        id: 4,
        person: 'Clara',
        avatar: null,
        week: 21,
        year: 2026,
        focus: 'Hotfix Skera v1.9.0 — résoudre les 3 critiques Sentry',
        blockers: ['Reproduction du bug en local impossible'],
        wins: ['2 critiques sur 3 résolus'],
    },
    {
        id: 5,
        person: 'Damien',
        avatar: null,
        week: 21,
        year: 2026,
        focus: 'Formation React avancé — OPCO',
        blockers: [],
        wins: ['Module hooks terminé', 'Exercices pratiques validés'],
    },
    {
        id: 6,
        person: 'Gaetan',
        avatar: null,
        week: 20,
        year: 2026,
        focus: 'OSDD compliance Gearup + intégration Sentry sur tous les frontends',
        blockers: [],
        wins: ['Structure OSDD validée', 'Widget Sentry déployé (4 frontends)', 'README mis à jour'],
    },
    {
        id: 7,
        person: 'Alice',
        avatar: null,
        week: 20,
        year: 2026,
        focus: 'Migration base de données Grosdata — préparation v2.4',
        blockers: ['Downtime prévu — coordination DevOps nécessaire'],
        wins: ['Script de migration rédigé et reviewé'],
    },
    {
        id: 8,
        person: 'Bob',
        avatar: null,
        week: 20,
        year: 2026,
        focus: 'Mise à jour dépendances Nexeren — patch sécurité',
        blockers: [],
        wins: ['0 breaking change', 'Tests e2e au vert'],
    },
    {
        id: 9,
        person: 'Clara',
        avatar: null,
        week: 20,
        year: 2026,
        focus: 'Skera — analyse des anomalies de perf signalées par le client',
        blockers: [],
        wins: ['Root cause identifiée : requête N+1 sur /dashboard'],
    },
    {
        id: 10,
        person: 'Damien',
        avatar: null,
        week: 20,
        year: 2026,
        focus: 'Setup CI/CD Nota — pipeline de déploiement automatique',
        blockers: [],
        wins: ['Pipeline opérationnel en staging', 'Déploiement prod en 4 min'],
    },
]

export const mockDeliveries: Delivery[] = [
    {
        id: 1,
        project: 'Grosdata',
        version: 'v2.4.1',
        date: '2026-05-22',
        tickets_resolved: 8,
        tickets_total: 11,
        notes: 'Refonte module rapports + correctif export CSV',
    },
    {
        id: 2,
        project: 'Nota',
        version: 'v3.2.0',
        date: '2026-05-21',
        tickets_resolved: 12,
        tickets_total: 12,
        notes: null,
    },
    {
        id: 3,
        project: 'Skera',
        version: 'v1.9.0',
        date: '2026-05-20',
        tickets_resolved: 3,
        tickets_total: 9,
        notes: 'Hotfix critique — déploiement d\'urgence (3 issues Sentry critiques)',
    },
    {
        id: 4,
        project: 'Pilota POC',
        version: 'v1.0.0',
        date: '2026-05-20',
        tickets_resolved: 16,
        tickets_total: 16,
        notes: 'SDK unifié + 4 frontends (Shoplab, Vota, Gearup, Pulse) + Sentry self-hosted',
    },
    {
        id: 5,
        project: 'Nexeren',
        version: 'v4.1.2',
        date: '2026-05-19',
        tickets_resolved: 5,
        tickets_total: 5,
        notes: 'Patch sécurité + mise à jour dépendances',
    },
]

export const mockMissions: Mission[] = [
    { id: 1, title: 'Formation OPCO React avancé — Damien', status: 'in_progress', category: 'opco', owner: 'Damien', due_date: '2026-06-01' },
    { id: 2, title: 'Formation OPCO TypeScript — Alice', status: 'todo', category: 'opco', owner: 'Alice', due_date: '2026-06-15' },
    { id: 3, title: 'Audit RGPD Grosdata — livrables DPO', status: 'in_progress', category: 'compliance', owner: 'Bob', due_date: '2026-05-30' },
    { id: 4, title: 'Mise en conformité cookies Skera', status: 'todo', category: 'compliance', owner: 'Clara', due_date: '2026-06-10' },
    { id: 5, title: 'Chefferie Skera v2 — roadmap Q3', status: 'in_progress', category: 'project_management', owner: 'Gaetan', due_date: null },
    { id: 6, title: 'Chefferie Grosdata — suivi client', status: 'in_progress', category: 'project_management', owner: 'Alice', due_date: null },
    { id: 7, title: 'Module export CSV Grosdata', status: 'done', category: 'features', owner: 'Alice', due_date: '2026-05-15' },
    { id: 8, title: 'SSO interne — Keycloak', status: 'blocked', category: 'features', owner: null, due_date: null },
    { id: 9, title: 'Dashboard Pulse — v1', status: 'in_progress', category: 'features', owner: 'Gaetan', due_date: '2026-05-31' },
    { id: 10, title: 'API unifiée Pilota SDK', status: 'done', category: 'features', owner: 'Gaetan', due_date: '2026-05-20' },
]

export const mockAbsences: Absence[] = [
    { id: 1, person: 'Bob',    days: ['lun', 'mar'],         reason: 'client',      note: 'Déplacement chez Nexeren (Lyon)' },
    { id: 2, person: 'Clara',  days: ['mer'],                reason: 'teletravail', note: null },
    { id: 3, person: 'Damien', days: ['lun', 'mar', 'mer', 'jeu', 'ven'], reason: 'formation', note: 'OPCO React — Paris' },
    { id: 4, person: 'Alice',  days: ['ven'],                reason: 'conge',       note: null },
]

export const mockDevOpsNeeds: DevOpsNeed[] = [
    { id: 1, title: 'Renouvellement cert SSL Skera', priority: 'critical', status: 'in_progress', owner: 'DevOps', project: 'Skera', notes: 'Expire le 28/05 — action urgente' },
    { id: 2, title: 'Upgrade PostgreSQL 15 → 16 (Grosdata)', priority: 'high', status: 'todo', owner: 'Damien', project: 'Grosdata', notes: 'Prévu fenêtre maintenance samedi 23/05' },
    { id: 3, title: 'Monitoring alerting Nota prod', priority: 'medium', status: 'in_progress', owner: 'Damien', project: 'Nota', notes: 'Grafana + Alertmanager configurés, tests en cours' },
    { id: 4, title: 'Backup vérification mensuelle', priority: 'low', status: 'done', owner: 'DevOps', project: null, notes: 'Tous les projets vérifiés OK' },
    { id: 5, title: 'Sentry self-hosted — config production', priority: 'medium', status: 'todo', owner: 'Gaetan', project: 'Pilota POC', notes: 'Installer getsentry/self-hosted sur le serveur XEFI' },
    { id: 6, title: 'CI/CD Pilota SDK — publication packages', priority: 'medium', status: 'todo', owner: 'Gaetan', project: 'Pilota POC', notes: 'Pipeline pnpm publish → npm registry interne' },
]

export const mockWeekInfos: WeekInfo[] = [
    { id: 1, type: 'event', title: 'Réunion équipe hebdo', detail: 'Mercredi 9h00 — présentiel + visio', date: '2026-05-20' },
    { id: 2, type: 'devtalk', title: 'DevTalk — Pilota SDK : retour d\'expérience', detail: 'Gaetan présente l\'architecture driver-based et les apprentissages du POC', date: '2026-05-21' },
    { id: 3, type: 'event', title: 'Demo Skera v1.9 chez le client', detail: 'Vendredi 14h00 — Clara + équipe client', date: '2026-05-23' },
    { id: 4, type: 'score', title: 'Satisfaction client Nota', detail: '4.8/5 — meilleur score du trimestre', date: null },
    { id: 5, type: 'score', title: 'Vélocité équipe S21', detail: '43 points — +12% vs S20', date: null },
    { id: 6, type: 'news', title: 'Nouveau contrat signé — Horizon v2', detail: 'Reprise du projet Horizon, démarrage Q3 2026', date: null },
]

export const mockRevenue: Revenue = {
    id: 1,
    period: 'Mai 2026',
    amount: 87400,
    target: 95000,
    annual_cumul: 412600,
    annual_target: 550000,
}

export const mockContracts: Contract[] = [
    { id: 1, type: 'franchise', count: 8, target: 10, value_k: 340 },
    { id: 2, type: 'propre',    count: 5, target: 8,  value_k: 215 },
]
