networks:
  pilota-proxy:
    external: true
    name: pilota-proxy

services:
  shoplab:
    build:
      context: ../..
      dockerfile: playground/nuxt/Dockerfile
    environment:
      NUXT_PUBLIC_TOLGEE_API_URL: http://tolgee.localhost
      NUXT_PUBLIC_TOLGEE_API_KEY: ${NUXT_PUBLIC_TOLGEE_API_KEY:-}
      NUXT_PUBLIC_SENTRY_DSN: ${NUXT_PUBLIC_SENTRY_DSN:-}
    networks:
      - default
      - pilota-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shoplab-${BRANCH:-dev}.rule=Host(`${BRANCH:-dev}-shoplab.localhost`)"
      - "traefik.http.routers.shoplab-${BRANCH:-dev}.entrypoints=web"
      - "traefik.http.services.shoplab-${BRANCH:-dev}.loadbalancer.server.port=3000"
